tdb-console/app/views/member.py
# -*- coding: utf-8 -*-
import urllib2
import flask_excel as excel

import time
from flask import Blueprint, render_template, request, jsonify, current_app
from flask import session
from flask_wtf import Form
from wtforms import StringField, PasswordField, HiddenField, FloatField, SelectField, IntegerField
from wtforms.validators import DataRequired, EqualTo

from app.template_helpers.utils import timestamp_to_str, format_currency
from app.views import Api, ApiError, AppError

# LEVEL_FLAG = [(0, u'无矿机'),
#               (1, u'铁矿机'),
#               (2, u'铜矿机'),
#               (3, u'银矿机'),
#               (4, u'金矿机'),
#               (5, u'钻矿机')]
from app.views.admin import api_permission

WALLET_TYPE_FLAG = [(1, u'总资产钱包'),
                    (2, u'社区钱包'),
                    (4, u'交易钱包')]
STATE_TYPE_FLAG = [('0', u'未完善资料'),
                   ('1', u'未通过测评'),
                   ('2', u'通过测评')]
MEMBER_LEVEL = [('0', u'普通会员'),
                ('1', u'节点会员')]

member = Blueprint('member', __name__)

api_permission['member'] = ['/admin/member', '/admin/wallet', '/admin/team']


class MemberFilterForm(Form):
    created_begin_timestamp = StringField('created_begin_timestamp')
    created_end_timestamp = StringField('created_end_timestamp')
    mobile = StringField('mobile')
    name = StringField('name')
    sponsor = StringField('sponsor')
    state = SelectField('state', choices=[('', u'全部')] + STATE_TYPE_FLAG, coerce=str)
    locked = SelectField('locked', choices=[('', u'全部'), ('1', u'锁定'), ('0', u'正常')])
    is_community_node = SelectField('is_community_node', choices=[('', u'全部')] + MEMBER_LEVEL, coerce=str)


class ChangePasswordForm(Form):
    password_id = HiddenField('password_id')
    password = PasswordField('password', validators=[DataRequired(u'请输入新的登录密码')])
    confirm_new_password = PasswordField('password', validators=[
        DataRequired(u'请再次输入新密码'), EqualTo('password', u'两次输入的密码不正确')])


class ChangeSecurityForm(Form):
    security_id = HiddenField('security_id')
    security_password = PasswordField('security_password', validators=[DataRequired(u'请输入新的安全密码')])
    confirm_new_password = PasswordField('security_password', validators=[
        DataRequired(u'请再次输入新密码'), EqualTo('security_password', u'两次输入的密码不正确')])


class ChangeProfileForm(Form):
    id = HiddenField('id')
    mobile = StringField('mobile')
    name = StringField('name')
    wechat = StringField('wechat')


class DepositForm(Form):
    id = HiddenField('id')
    assets_type = SelectField('assets_type', choices=WALLET_TYPE_FLAG, coerce=int)
    amount = FloatField('amount', validators=[DataRequired(u'请输入充值数额')])


class PaymentForm(Form):
    user_id = HiddenField('user_id')
    type = IntegerField('type')
    name = StringField('name')
    bank = StringField('bank')
    card_number = StringField('card_number')
    wechat = StringField('wechat')
    wechat_image = StringField('wechat_image')
    alipay = StringField('alipay')
    alipay_image = StringField('alipay_image')
    address = StringField('address')
    remark = StringField('remark')


@member.route('/')
def index():
    filter_form = MemberFilterForm()
    return render_template('member/list.html',
                           STATE_TYPE_FLAG=dict(STATE_TYPE_FLAG),
                           MEMBER_LEVEL=dict(MEMBER_LEVEL),
                           filter_form=filter_form)


@member.route('/details/<string:member_id>')
def details(member_id):
    deposit_form = DepositForm()
    change_password_form = ChangePasswordForm()
    change_security_form = ChangeSecurityForm()
    change_profile_form = ChangeProfileForm()
    payment_form = PaymentForm()
    data = Api.get('/admin/member/detail/' + urllib2.quote(member_id))
    change_security_form.security_id.data = data['id']
    change_password_form.password_id.data = data['id']
    change_profile_form.id.data = data['id']
    deposit_form.id.data = data['assets']['id']
    payment_form.user_id.data = data['id']
    change_profile_form.mobile.data = data['mobile']
    change_profile_form.name.data = data['name']
    change_profile_form.wechat.data = data['wechat']
    payment_list = Api.get('/admin/payment/list', {'user_id': data['id']})['objects']

    payment_dic = {}
    payment_flag = ['bank_payment', 'wechat_payment', 'alipay_payment', 'usdt_payment']
    for item in payment_list:
        payment_dic[payment_flag[item['type']]] = item

    return render_template('member/details.html', data=data,
                           payment_dic=payment_dic, payment_form=payment_form,
                           change_password_form=change_password_form, change_profile_form=change_profile_form,
                           change_security_form=change_security_form, deposit_form=deposit_form)


@member.route('/ajax/list', methods=['POST'])
def ajax_list():
    params = request.get_json()
    if params['query'].get('created_begin_timestamp'):
        params['query']['created_begin_timestamp'] = int(time.mktime(
            time.strptime(params['query']['created_begin_timestamp'], u"%Y年%m月%d日")))
    if params['query'].get('created_end_timestamp'):
        params['query']['created_end_timestamp'] = int(time.mktime(
            time.strptime(params['query']['created_end_timestamp'] + u' 23:59:59', u"%Y年%m月%d日 %H:%M:%S")))
    data = Api.get('/admin/member', params['query'])
    total_records = data['total_count']
    return_dict = {
        'draw': params['draw'],
        'recordsTotal': total_records,
        'recordsFiltered': total_records,
        'data': data['objects']
    }
    return jsonify(return_dict)


@member.route('/ajax/lock', methods=['POST'])
def ajax_lock():
    params = request.get_json()
    user_id = params.pop('id')
    data = Api.put('/admin/member/detail/' + urllib2.quote(user_id), params)
    return jsonify(data)


@member.route('/ajax/delete/payment', methods=['POST'])
def ajax_delete_payment():
    params = request.get_json()
    user_id = params.pop('id')
    data = Api.delete('/admin/payment/details/' + urllib2.quote(user_id))
    return jsonify(data)


@member.route('/ajax/change_password', methods=['POST'])
def ajax_change_password():
    change_password_form = ChangePasswordForm()
    if change_password_form.validate():
        data = Api.put('/admin/member/detail/' + urllib2.quote(change_password_form.password_id.data), {
            'password': change_password_form.password.data
        })
        return jsonify(data)
    else:
        raise ApiError(AppError.INVALID_REQUEST, change_password_form.errors)


@member.route('/ajax/add_payment', methods=['POST'])
def ajax_add_payment():
    payment_form = PaymentForm()
    if payment_form.validate():
        data = Api.post('/admin/payment/list', payment_form.data)
        return jsonify(data)
    else:
        raise ApiError(AppError.INVALID_REQUEST, payment_form.errors)


@member.route('/ajax/change_security', methods=['POST'])
def ajax_change_security():
    change_security_form = ChangeSecurityForm()
    if change_security_form.validate():
        data = Api.put('/admin/member/detail/' + urllib2.quote(change_security_form.security_id.data), {
            'security_password': change_security_form.security_password.data
        })
        return jsonify(data)
    else:
        raise ApiError(AppError.INVALID_REQUEST, change_security_form.errors)


@member.route('/ajax/change_profile', methods=['POST'])
def ajax_change_profile():
    change_profile_form = ChangeProfileForm()
    if change_profile_form.validate():
        data = Api.put('/admin/member/detail/' + urllib2.quote(change_profile_form.id.data), change_profile_form.data)
        return jsonify(data)
    else:
        raise ApiError(AppError.INVALID_REQUEST, change_profile_form.errors)


@member.route('/ajax/deposit', methods=['POST'])
def ajax_deposit():
    deposit_form = DepositForm()
    if deposit_form.validate():
        data = Api.post('/admin/assets/recharge', deposit_form.data)
        return jsonify(data)
    else:
        raise ApiError(AppError.INVALID_REQUEST, deposit_form.errors)


@member.route('/sponsor')
def sponsor():
    return render_template('member/sponsor_tree.html')


@member.route('/ajax/sponsor/downline', methods=['POST'])
def ajax_sponsor_downline():
    params = request.json
    res = Api.get('/admin/team/sponsor_downline', {'unique_id': params['unique_id']})
    children = []
    for item in res['objects']:
        obj = {'id': item['mobile'], 'text': u'{} {}'.format(item['name'], item['mobile']), 'children': True,
               'icon': 'fa fa-user'}
        children.append(obj)
    result = {
        'id': params['unique_id'],
        'text': params['text'],
        'icon': 'fa fa-user',
        'children': children
    }
    return jsonify(result)


@member.route('/binary', methods=['GET'])
def binary():
    return render_template('member/binary_tree.html')


@member.route('/ajax/placement/downline', methods=['POST'])
def ajax_placement_downline():
    params = request.json
    res = Api.get('/admin/team/placement_downline', params)
    return jsonify(res)


@member.route('/data/download')
def data_download():
    params = {}
    for key, value in request.args.items():
        if value != '':
            params[key] = value

    params['per_page'] = 10000
    if params.get('created_begin_timestamp'):
        params['created_begin_timestamp'] = int(time.mktime(
            time.strptime(params['created_begin_timestamp'], u"%Y年%m月%d日")))
    if params.get('created_end_timestamp'):
        params['created_end_timestamp'] = int(time.mktime(
            time.strptime(params['created_end_timestamp'] + u' 23:59:59', u"%Y年%m月%d日 %H:%M:%S")))

    params['per_page'] = 10000
    member_data = Api.get('/admin/member', params)
    lock_status = {1: u'锁定', 0: u'未锁定'}
    fields = [[u'昵称',
               u'手机号',
               u'编号',
               u'推荐人',
               u'安置上线',
               u'零钱包',
               u'冷钱包',
               u'静态收益',
               u'动态收益',

tdb-console/app/views/register.py
# -*- coding: utf-8 -*-
import urllib2

from flask import Blueprint, jsonify
from flask import render_template
from flask import request
from flask_wtf import Form
from wtforms import StringField, SelectField, TextAreaField, HiddenField
from wtforms.validators import DataRequired

from app.views import Api, ApiError, AppError
from app.views.admin import api_permission

register = Blueprint('register', __name__)
api_permission['register'] = ['/admin/member']


class RegisterForm(Form):
    mobile = StringField('mobile', validators=[DataRequired(u'请填写手机号')])
    sponsor = StringField('sponsor', validators=[DataRequired(u'请填写推荐人')])
    password = StringField('password', validators=[DataRequired(u'请填写密码')])
    security_password = StringField('security_password', validators=[DataRequired(u'请填写密码')])


@register.route('/register/member')
def register_member():
    form = RegisterForm()
    return render_template('member/register.html', form=form)


@register.route('/ajax/register_member', methods=['POST'])
def ajax_register_member():
    form = RegisterForm()
    if form.validate():
        data = form.data
        return jsonify(Api.post('/admin/member', data))
    else:
        raise ApiError(AppError.INVALID_REQUEST, form.errors)

tdb-console/app/templates/member/binary_tree.html
{% extends 'layout/main.html' %}
{% set title = '双规网络图' %}

{% block head %}
    <!-- build:css /static/components/binaryTree..min.css -->
    <link rel="stylesheet" href="/static/assets/css/jquery.contextMenu.css">
    <link rel="stylesheet" href="/static/assets/css/binary.tree.css">
    <!-- endbuild -->
{% endblock %}


{% block content %}


    <div class="panel bg-no">
        <div class="panel-body clearfix">
            <div class="search-item">
                <label>用户名</label>
                <input type="text" placeholder="请输入用户名" id="user_id" class="form-control">
            </div>
            <div class="search-item search-tabtn">
                <button type="button" id="search" class="btn btn-primary btn-flat">查询</button>
            </div>
        </div>
    </div>

    <section class="panel">
        <div class="panel-body">
            <div class="tree" id="tree">
                <div class="wrap">
                    <div class="struct"></div>
                </div>
                <!--<div class="search">-->
                <!--<div class="form-group clearfix">-->
                <!--<input type="text" class="form-control ipt" value="right-1" name="username">-->
                <!--<input type="button" class="btn btn-primary" value="搜索">-->
                <!--</div>-->
                <!--</div>-->
            </div>
        </div>
    </section>

{% endblock %}


{% block script %}
    <!-- build:js /static/components/binaryTree.min.js -->
    <script src="/static/assets/data/mockData.js"></script>
    <script src="/static/assets/js/jquery.ui.position.js"></script>
    <script src="/static/assets/js/jquery.contextMenu.js"></script>
    <script src="/static/assets/js/binaryTree/binary.tree.js"></script>
    <!-- endbuild -->
    <script type="text/javascript">
        $(function () {
            binaryTree(2, {
                id: '#tree',
                url: '{{ url_for("member.ajax_placement_downline") }}',
                addUrl: '{{ url_for('member.index') }}',
                unique_id: '{{ 'root' if not request.args.get('user_id') else request.args.get('user_id') }}',
                toolTip: function (data) {
                    var html = '<ul class="list">';
                    html += '<li><span>编号：</span><em>' + data.uid + '</em></li>';
                    html += '<li><span>昵称：</span><em>' + data.nickname + '</em></li>';
                    html += '<li><span>注册时间：</span><em>' + data.created_at + '</em></li>';
                    html += '<li><span>左区业绩：</span><em>' + data.team_a_investment + '</em></li>';
                    html += '<li><span>右区业绩：</span><em>' + data.team_b_investment + '</em></li>';
                    html += '</ul>';
                    return html;
                },
                ajaxErrorCallback: function (err) {
                    console.error(err);
                },
                searchBtn: $('#search'),
                searchInput: $('#user_id')
            });
        });
    </script>

{% endblock %}

tdb-console/app/templates/member/list.html
{% extends 'layout/main.html' %}
{% set title = '会员列表' %}

{% block content %}
    <div class="panel bg-no">
        <form id="filter-form">
            <div class="panel-body clearfix">
                <div class="search-item">
                    <label>手机号</label>
                    {{ filter_form.mobile(class='form-control') }}
                </div>
                <div class="search-item">
                    <label>姓名</label>
                    {{ filter_form.name(class='form-control') }}
                </div>
                <div class="search-item">
                    <label>推荐人手机</label>
                    {{ filter_form.sponsor(class='form-control') }}
                </div>
                <div class="search-item">
                    <label>状态</label>
                    {{ filter_form.state(class='form-control') }}
                </div>
                <div class="search-item">
                    <label>锁定</label>
                    {{ filter_form.locked(class='form-control') }}
                </div>
                <div class="search-item">
                    <label>会员级别</label>
                    {{ filter_form.is_community_node(class='form-control') }}
                </div>
                <div class="search-item-date">
                    <label>时间：</label>
                    <div class="has-feedback">
                        {{ filter_form.created_begin_timestamp(class_='form-control font-12') }}
                        <span class="icon-calendar h4 no-m form-control-feedback" aria-hidden="true"></span>
                    </div>
                    <span class="date-line">-</span>
                    <div class="has-feedback">
                        {{ filter_form.created_end_timestamp(class_='form-control font-12') }}
                        <span class="icon-calendar h4 no-m form-control-feedback" aria-hidden="true"></span>
                    </div>
                </div>
                <div class="search-item search-tabtn">
                    <button type="submit" class="btn btn-primary btn-flat">查询</button>
                </div>
                {#                <div class="search-item search-tabtn">#}
                {#                    <button id="download" class="btn btn-warning">导出Excel</button>#}
                {#                </div>#}
            </div>
        </form>
    </div>
    <div class="panel panel-default">
        <div>
            <table class="table table-striped data-table font-12" id="admin-table">
                <thead>
                <tr>
                    {#                    <th><span class="row-select-checkbox"></span></th>#}
                    <th class="text-center">姓名</th>
                    <th class="text-center">手机号</th>
                    <th class="text-center">微信号</th>
                    <th class="text-center">用户ID</th>
                    <th class="text-center">会员级别</th>
                    <th class="text-center">推荐手机</th>
                    <th class="text-center">推荐姓名</th>
                    <th class="text-center">状态</th>
                    <th class="text-center">锁定</th>
                    <th class="text-center">注册时间</th>
                    <th class="text-center">操作</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>

    <script id="operation-template" type="text/template">
        <a class="label btn-primary" href="{{ url_for('member.details',member_id='') }}${data}">查看详情</a>
        {% raw %}
        {{if row.locked}}
        <a data-id="${data}" data-lock="${row.locked}" class="label btn-default change-lock">
            解锁
        </a>
        {{else}}
        <a data-id="${data}" data-lock="${row.locked}" class="label btn-danger change-lock">
            锁定
        </a>
        {{/if}}
        &nbsp
        {{if row.transaction_level}}
        <a data-id="${data}" data-transaction_level="${row.transaction_level}"
           class="label btn-warning change-transaction">
            取消系统挂卖
        </a>
        {{else}}
        <a data-id="${data}" data-transaction_level="${row.transaction_level}"
           class="label btn-danger change-transaction">
            系统挂卖
        </a>
        {{/if}}
        &nbsp
        <a data-id="${data}" class="label btn-danger change-delete">
            删除
        </a>
        {% endraw %}
    </script>

    <!-- /.table-responsive -->
{% endblock %}

{% block script %}
    <!-- build:js /static/components/bootstrap-datepicker.min.js -->
    <script src="/static/components/quantum/js/bootstrap-datepicker.js"></script>
    <script src="/static/components/quantum/js/locales/bootstrap-datepicker.zh-CN.js"></script>
    <!-- endbuild -->
    <script>
        $(function () {
            $('#created_begin_timestamp,#created_end_timestamp').datepicker({
                language: 'zh-CN'
            });
            var stateTypeFlag = {{ STATE_TYPE_FLAG | tojson }};
            var memberLevel = {{ MEMBER_LEVEL | tojson }};
            $("#download").on('click', function () {

                window.open("{{ url_for('member.data_download') }}?" +
                    'mobile=' + $('#mobile').val() +
                    '&uid=' + $('#uid').val() +
                    '&sponsor=' + $('#sponsor').val() +
                    '&locked=' + $('#locked').val() +
                    '&created_begin_timestamp=' + $('#created_begin_timestamp').val() +
                    '&created_end_timestamp=' + $('#created_end_timestamp').val());
            });
            var lockStatus = {1: '锁定', 0: '未锁定'};
            var filterForm = $('#filter-form');
            var defaultRowOptions = {className: 'v-middle text-center'};
            var $table = $('#admin-table');
            window.table = $table.DataTable(dtUtils.config({
                select: {
                    style: 'os',
                    selector: '.row-select-checkbox'
                },
                columns: [
                    dtUtils.columns.text('name', defaultRowOptions),
                    dtUtils.columns.text('mobile', defaultRowOptions),
                    dtUtils.columns.text('wechat', defaultRowOptions),
                    dtUtils.columns.text('uid', defaultRowOptions),
                    dtUtils.columns.dict('is_community_node', memberLevel, defaultRowOptions),
                    dtUtils.columns.text('sponsor.mobile', defaultRowOptions),
                    dtUtils.columns.text('sponsor.name', defaultRowOptions),

                    dtUtils.columns.dict('state', stateTypeFlag, defaultRowOptions),
                    dtUtils.columns.dict('locked', lockStatus, defaultRowOptions),
                    dtUtils.columns.date('created_timestamp', defaultRowOptions),
                    dtUtils.columns.tmpl('id', '#operation-template', defaultRowOptions)
                ],
                serverSide: true,
                ajax: dtUtils.dataLoader('{{ url_for('member.ajax_list') }}', filterForm)
            }));
            filterForm.submit(function (e) {
                e.preventDefault();
                table.ajax.reload();
                return false;
            });

            $table.on('click', '.change-lock', function () {
                var text = $(this).text();
                var $this = $(this);
                var targetLocked = $(this).data('lock') ? 0 : 1;
                layer.confirm('确认要' + text + '这个会员吗？', {
                    btn: ['确认', '取消']
                    , btn2: function (index, layero) {
                    }
                }, function (index) {
                    var loadingIndex = layer.load();
                    $.ajax({
                        type: 'POST',
                        contentType: 'application/json',
                        data: JSON.stringify({id: $this.data('id'), locked: targetLocked}),
                        url: '{{ url_for('member.ajax_lock') }}',
                        success: function () {
                            layer.msg(text + '成功！');
                            table.ajax.reload();
                        },
                        error: function () {
                            layer.msg('操作失败');
                        }
                    }).always(function () {
                        layer.close(loadingIndex);
                    });
                });
            });
            $table.on('click', '.change-delete', function () {
                var text = $(this).text();
                var $this = $(this);
                layer.confirm('确认要' + text + '这个会员吗？', {
                    btn: ['确认', '取消']
                    , btn2: function (index, layero) {
                    }
                }, function (index) {
                    var loadingIndex = layer.load();
                    $.ajax({
                        type: 'POST',
                        contentType: 'application/json',
                        data: JSON.stringify({id: $this.data('id'), locked: 2}),
                        url: '{{ url_for('member.ajax_lock') }}',
                        success: function () {
                            layer.msg(text + '成功！');
                            table.ajax.reload();
                        },
                        error: function (xhr) {
                            if (xhr.responseJSON.message.sponsor_id) {
                                layer.msg('该会员已经注册下线');
                            } else {
                                layer.msg('该会员已经产生业绩');
                            }

                        }
                    }).always(function () {
                        layer.close(loadingIndex);
                    });
                });
            });

            $table.on('click', '.change-transaction', function () {
                var text = $(this).text();
                var $this = $(this);
                var transaction_level = $(this).data('transaction_level') ? 0 : 2;
                layer.confirm('确认要' + text + '吗？', {
                    btn: ['确认', '取消']
                    , btn2: function (index, layero) {
                    }
                }, function (index) {
                    var loadingIndex = layer.load();
                    $.ajax({
                        type: 'POST',
                        contentType: 'application/json',
                        data: JSON.stringify({id: $this.data('id'), transaction_level: transaction_level}),
                        url: '{{ url_for('member.ajax_lock') }}',
                        success: function () {
                            layer.msg(text + '成功！');
                            table.ajax.reload();
                        },
                        error: function () {
                            layer.msg('操作失败');
                        }
                    }).always(function () {
                        layer.close(loadingIndex);
                    });
                });
            });

            $table.on('click', '.change-password', function () {
                $('#id').val($(this).data('id'));
                $('.admin-uid').text($(this).data('uid'));
                $('#password').val('');
                $('#changePasswordModal').modal('show');
            });

            $table.on('click', '.change-role', function () {
                $('#user_id').val($(this).data('id'));
                $('.admin-uid').text($(this).data('uid'));
                $('#role').val($(this).data('role'));
                $('#changeRoleModal').modal('show');
            });

            $('#changePasswordForm').submit(function (e) {
                e.preventDefault();
                var index = layer.load();
                $('#changePasswordForm').resetFieldErrors().ajaxSubmit(function () {
                    $('#changePasswordForm').modal('hide');
                    layer.msg('操作成功', function () {
                        location.reload();
                    });
                }).error(function (xhr) {
                    if ($('#changePasswordForm').applyFieldErrors(xhr, {
                            handler: 'popover-and-highlight'
                        })) {
                        layer.msg('信息填写错误');
                    }
                }).always(function () {
                    layer.close(index);
                });
            });

            $('#changeRoleForm').submit(function (e) {
                e.preventDefault();
                var index = layer.load();
                $('#changeRoleForm').resetFieldErrors().ajaxSubmit(function () {
                    $('#changeRoleForm').modal('hide');
                    layer.msg('操作成功', function () {
                        location.reload();
                    });
                }).error(function (xhr) {
                    if ($('#changeRoleForm').applyFieldErrors(xhr, {
                            handler: 'popover-and-highlight'
                        })) {
                        layer.msg('信息填写错误');
                    }
                }).always(function () {
                    layer.close(index);
                });
            });
        });
    </script>
{% endblock %}