tdb-console/app/views/analyze.py
# -*- coding: utf-8 -*-
import time

import decimal
from flask import Blueprint
from flask import render_template
from flask import request
import flask_excel as excel
from flask_wtf import Form
from wtforms import StringField

from app.template_helpers.utils import format_currency
from app.views import Api
from app.views.admin import api_permission

analyze = Blueprint('analyze', __name__)
api_permission['analyze'] = ['/admin/wallet']


class FilterForm(Form):
    created_begin_timestamp = StringField('created_begin_timestamp')
    created_end_timestamp = StringField('created_end_timestamp')


def filter_params(filter_form):
    params = {}

    if request.args.get('created_begin_timestamp'):
        params['created_begin_timestamp'] = int(time.mktime(
            time.strptime(request.args.get('created_begin_timestamp'), u"%Y年%m月%d日")))
        filter_form.created_begin_timestamp.data = request.args.get('created_begin_timestamp')
    if request.args.get('created_end_timestamp'):
        params['created_end_timestamp'] = int(time.mktime(
            time.strptime(request.args.get('created_end_timestamp') + u' 23:59:59', u"%Y年%m月%d日 %H:%M:%S")))
        filter_form.created_end_timestamp.data = request.args.get('created_end_timestamp')

    return params


@analyze.route('/')
def index():
    filter_form = FilterForm()
    params = filter_params(filter_form)
    analysis_data = Api.get('/admin/wallet/day/statistics', params)

    data = [[k,
             format_currency(v.get('recharge', '0')),
             format_currency(v.get('deduction', '0')),
             format_currency(v.get('static_profit', '0')),
             format_currency(v.get('dynamic_profit', '0')),
             format_currency(v.get('node_profit', '0')),
             format_currency(v.get('free_coin', '0')),
             format_currency(v.get('transfer', '0')),
             format_currency(v.get('withdraw', '0')),
             format_currency(v.get('block_recharge', '0')),
             format_currency(v.get('buy_product', '0')),
             format_currency(v.get('reinvestment', '0')),
             format_currency(v.get('buy_order', '0')),
             format_currency(v.get('sell_order', '0')),
             ] for k, v in analysis_data.items()]
    day_data = sorted(data, key=lambda x: x[0])

    recharge = sum([decimal.Decimal(x[1]) for x in data])
    deduction = sum([decimal.Decimal(x[2]) for x in data])
    static_profit = sum([decimal.Decimal(x[3]) for x in data])
    dynamic_profit = sum([decimal.Decimal(x[4]) for x in data])
    node_profit = sum([decimal.Decimal(x[5]) for x in data])
    free_coin = sum([decimal.Decimal(x[6]) for x in data])
    transfer = sum([decimal.Decimal(x[7]) for x in data])
    withdraw = sum([decimal.Decimal(x[8]) for x in data])
    block_recharge = sum([decimal.Decimal(x[9]) for x in data])
    buy_product = sum([decimal.Decimal(x[10]) for x in data])
    reinvestment = sum([decimal.Decimal(x[11]) for x in data])
    buy_order = sum([decimal.Decimal(x[12]) for x in data])
    sell_order = sum([decimal.Decimal(x[13]) for x in data])

    data = {
        'recharge': format_currency(recharge),
        'deduction': format_currency(deduction),
        'static_profit': format_currency(static_profit),
        'dynamic_profit': format_currency(dynamic_profit),
        'node_profit': format_currency(node_profit),
        'free_coin': format_currency(free_coin),
        'transfer': format_currency(transfer),
        'withdraw': format_currency(withdraw),
        'block_recharge': format_currency(block_recharge),
        'buy_product': format_currency(buy_product),
        'reinvestment': format_currency(reinvestment),
        'buy_order': format_currency(buy_order),
        'sell_order': format_currency(sell_order),
    }

    return render_template('wallet/analyze.html',
                           filter_form=filter_form,
                           day_data=day_data,
                           data=data)


@analyze.route('/download')
def download():
    filter_form = FilterForm()
    params = filter_params(filter_form)
    analysis_data = Api.get('/admin/wallet/day/statistics', params)

    fields = [[u'时间',
               u'系统充值',
               u'系统扣减',
               u'静态收益',
               u'动态收益',
               u'节点收益',
               u'冻结释放',
               u'转账',
               u'提币',
               u'区块充值',
               u'购买商品',
               u'复投',
               u'交易(买单)',
               u'交易(卖单)']]

    data = [[k,
             format_currency(v.get('recharge', '0')),
             format_currency(v.get('deduction', '0')),
             format_currency(v.get('static_profit', '0')),
             format_currency(v.get('dynamic_profit', '0')),
             format_currency(v.get('node_profit', '0')),
             format_currency(v.get('free_coin', '0')),
             format_currency(v.get('transfer', '0')),
             format_currency(v.get('withdraw', '0')),
             format_currency(v.get('block_recharge', '0')),
             format_currency(v.get('buy_product', '0')),
             format_currency(v.get('reinvestment', '0')),
             format_currency(v.get('buy_order', '0')),
             format_currency(v.get('sell_order', '0')),
             ] for k, v in analysis_data.items()]
    day_data = sorted(data, key=lambda x: x[0])

    recharge = sum([decimal.Decimal(x[1]) for x in data])
    deduction = sum([decimal.Decimal(x[2]) for x in data])
    static_profit = sum([decimal.Decimal(x[3]) for x in data])
    dynamic_profit = sum([decimal.Decimal(x[4]) for x in data])
    node_profit = sum([decimal.Decimal(x[5]) for x in data])
    free_coin = sum([decimal.Decimal(x[6]) for x in data])
    transfer = sum([decimal.Decimal(x[7]) for x in data])
    withdraw = sum([decimal.Decimal(x[8]) for x in data])
    block_recharge = sum([decimal.Decimal(x[9]) for x in data])
    buy_product = sum([decimal.Decimal(x[10]) for x in data])
    reinvestment = sum([decimal.Decimal(x[11]) for x in data])
    buy_order = sum([decimal.Decimal(x[12]) for x in data])
    sell_order = sum([decimal.Decimal(x[13]) for x in data])

    total = [[u'合计',
              format_currency(recharge),
              format_currency(deduction),
              format_currency(static_profit),
              format_currency(dynamic_profit),
              format_currency(node_profit),
              format_currency(free_coin),
              format_currency(transfer),
              format_currency(withdraw),
              format_currency(block_recharge),
              format_currency(buy_product),
              format_currency(reinvestment),
              format_currency(buy_order),
              format_currency(sell_order)]]

    return excel.make_response_from_array(fields + day_data + total, "xls", file_name='财务统计')

tdb-console/app/views/wallet.py
# -*- coding: utf-8 -*-

import time
import decimal
import urllib2

import flask_excel as excel
from flask import Blueprint, render_template, request, jsonify
from flask_wtf import Form
from wtforms import StringField, SelectField

from app.template_helpers.utils import timestamp_to_str, format_currency
from app.views import Api
from app.views.admin import api_permission

wallet = Blueprint('wallet', __name__)
api_permission['wallet'] = ['/admin/withdraw', '/admin/wallet']

CHOOSE_ALL = [('', u'全部')]

WALLET_TYPE_FLAG = [('1', u'总资产钱包'),
                    ('2', u'社区钱包'),
                    ('4', u'交易钱包')]

AMOUNT_TYPE = [('0', u'全部'),
               ('1', u'>=0'),
               ('2', u'<0')]

TYPE_FLAG = [(1, u'测评奖励'),
             (2, u'充值'),
             (4, u'买'),
             (8, u'卖'),
             (16, u'推荐奖励'),
             (32, u'买卖释放'),
             (64, u'加速释放'),
             (128, u'兑换'),
             (256, u'转账'),
             (512, u'分红')
             ]

STATUS_FLAG = [(1, u'申请'),
               (2, u'完成'),
               (4, u'驳回')]


class FilterForm(Form):
    created_begin_timestamp = StringField('created_begin_timestamp')
    created_end_timestamp = StringField('created_end_timestamp')
    record_type = SelectField('record_type', choices=CHOOSE_ALL + TYPE_FLAG)
    amount_type = SelectField('amount_type', choices=AMOUNT_TYPE)
    assets_type = SelectField('assets_type', choices=CHOOSE_ALL + WALLET_TYPE_FLAG)
    mobile = StringField('mobile')


class WithdrawForm(Form):
    created_begin_timestamp = StringField('created_begin_timestamp')
    created_end_timestamp = StringField('created_end_timestamp')
    currency_code = SelectField('currency_code', choices=CHOOSE_ALL + WALLET_TYPE_FLAG)
    status = SelectField('status', choices=CHOOSE_ALL + STATUS_FLAG)


class AssetsForm(Form):
    currency_code = SelectField('currency_code', choices=CHOOSE_ALL + WALLET_TYPE_FLAG)
    assets_type = SelectField('assets_type', choices=CHOOSE_ALL + WALLET_TYPE_FLAG)
    address = StringField('address')
    uid = StringField('uid')
    mobile = StringField('mobile')


@wallet.route('/')
def index():
    filter_form = FilterForm()
    return render_template('wallet/wallet.html', filter_form=filter_form, TYPE_FLAG=dict(TYPE_FLAG),
                           WALLET_TYPE_FLAG=dict(WALLET_TYPE_FLAG))


@wallet.route('/assets')
def assets():
    filter_form = AssetsForm()
    return render_template('wallet/assets.html', filter_form=filter_form)


@wallet.route('/withdraw')
def withdraw():
    filter_form = WithdrawForm()
    return render_template('wallet/withdraw.html',
                           filter_form=filter_form,
                           STATUS_FLAG=dict(STATUS_FLAG))


@wallet.route('/ajax/list', methods=['POST'])
def ajax_list():
    params = request.get_json()
    if params['query'].get('created_begin_timestamp'):
        params['query']['created_begin_timestamp'] = int(time.mktime(
            time.strptime(params['query']['created_begin_timestamp'], u"%Y年%m月%d日")))
    if params['query'].get('created_end_timestamp'):
        params['query']['created_end_timestamp'] = int(time.mktime(
            time.strptime(params['query']['created_end_timestamp'] + u' 23:59:59', u"%Y年%m月%d日 %H:%M:%S")))
    data = Api.get('/admin/assets/record', params['query'])
    total_records = data['total_count']
    return_dict = {
        'draw': params['draw'],
        'recordsTotal': total_records,
        'recordsFiltered': total_records,
        'data': data['objects']
    }
    return jsonify(return_dict)


@wallet.route('/ajax/withdraw_list', methods=['POST'])
def ajax_withdraw_list():
    params = request.get_json()
    if params['query'].get('created_begin_timestamp'):
        params['query']['created_begin_timestamp'] = int(time.mktime(
            time.strptime(params['query']['created_begin_timestamp'], u"%Y年%m月%d日")))
    if params['query'].get('created_end_timestamp'):
        params['query']['created_end_timestamp'] = int(time.mktime(
            time.strptime(params['query']['created_end_timestamp'] + u' 23:59:59', u"%Y年%m月%d日 %H:%M:%S")))
    data = Api.get('/admin/order', params['query'])
    total_records = data['total_count']
    return_dict = {
        'draw': params['draw'],
        'recordsTotal': total_records,
        'recordsFiltered': total_records,
        'data': data['objects']
    }
    return jsonify(return_dict)


@wallet.route('/ajax/assets_list', methods=['POST'])
def assets_ajax_list():
    params = request.get_json()

    data = Api.get('/admin/assets', params['query'])
    total_records = data['total_count']
    return_dict = {
        'draw': params['draw'],
        'recordsTotal': total_records,
        'recordsFiltered': total_records,
        'data': data['objects']
    }
    return jsonify(return_dict)


@wallet.route('/ajax/withdraw/confirm', methods=['POST'])
def ajax_withdraw_confirm():
    params = request.get_json()
    result = Api.post('/admin/order/withdraw/confirm/' + urllib2.quote(str(params['number'])), {})
    return jsonify(result)


@wallet.route('/ajax/withdraw/cancel', methods=['POST'])
def ajax_withdraw_cancel():
    params = request.get_json()
    result = Api.post('/admin/order/withdraw/cancel/' + urllib2.quote(str(params['number'])), {})
    return jsonify(result)


@wallet.route('/ajax/recharge', methods=['POST'])
def ajax_recharge():
    params = request.get_json()
    result = Api.post('/admin/assets/recharge', params)
    return jsonify(result)


@wallet.route('/withdraw/download')
def withdraw_download():
    params = {}
    for key, value in request.args.items():
        if value != '':
            params[key] = value

    params['per_page'] = 10000
    if params.get('created_begin_timestamp'):
        params['created_begin_timestamp'] = int(time.mktime(
            time.strptime(params['created_begin_timestamp'], u"%Y年%m月%d日")))
    if params.get('created_end_timestamp'):
        params['created_end_timestamp'] = int(time.mktime(
            time.strptime(params['created_end_timestamp'] + u' 23:59:59', u"%Y年%m月%d日 %H:%M:%S")))

    params['per_page'] = 10000
    member_data = Api.get('/admin/withdraw', params)
    status = dict(STATUS_FLAG)
    fields = [[u'时间',
               u'用户编号',
               u'提现数量',
               u'手续费',
               u'提现地址',
               u'交易哈希',
               u'状态']]

    data = [[timestamp_to_str(y['created_timestamp']),
             y['user']['uid'],
             format_currency(y['amount']),
             format_currency(y['fee']),
             y['address'],
             y['txid'],
             status[y['status']]]
            for y in member_data['items']]

    return excel.make_response_from_array(fields + data, "xls", file_name='提现')


@wallet.route('/record/download')
def record_download():
    params = {}
    for key, value in request.args.items():
        if value != '':
            params[key] = value

    params['per_page'] = 10000
    if params.get('created_begin_timestamp'):
        params['created_begin_timestamp'] = int(time.mktime(
            time.strptime(params['created_begin_timestamp'], u"%Y年%m月%d日")))
    if params.get('created_end_timestamp'):
        params['created_end_timestamp'] = int(time.mktime(
            time.strptime(params['created_end_timestamp'] + u' 23:59:59', u"%Y年%m月%d日 %H:%M:%S")))

    params['per_page'] = 10000
    member_data = Api.get('/admin/wallet/record', params)
    wallet_type = dict(WALLET_TYPE_FLAG)
    type_flag = dict(TYPE_FLAG)

    fields = [[u'创建时间',
               u'用户编号',
               u'变化后余额',
               u'变化量',
               u'钱包类型',
               u'来源',
               u'详情信息']]

    data = [[timestamp_to_str(y['created_timestamp']),
             y['user']['uid'],
             format_currency(y['current_amount']),
             format_currency(y['delta_amount']),
             wallet_type[y['wallet_type']],
             type_flag[y['type']],
             y['details']['message']]
            for y in member_data['items']]

    return excel.make_response_from_array(fields + data, "xls", file_name='钱包记录')


def filter_params(filter_form):
    params = {}

    if request.args.get('created_begin_timestamp'):
        params['created_begin_timestamp'] = int(time.mktime(
            time.strptime(request.args.get('created_begin_timestamp'), u"%Y年%m月%d日")))
        filter_form.created_begin_timestamp.data = request.args.get('created_begin_timestamp')
    if request.args.get('created_end_timestamp'):
        params['created_end_timestamp'] = int(time.mktime(
            time.strptime(request.args.get('created_end_timestamp') + u' 23:59:59', u"%Y年%m月%d日 %H:%M:%S")))
        filter_form.created_end_timestamp.data = request.args.get('created_end_timestamp')

    return params


@wallet.route('/analyze')
def analyze():
    filter_form = FilterForm()
    params = filter_params(filter_form)
    analysis_data = Api.get('/admin/wallet/day/statistics', params)

    data = [[k,
             format_currency(v.get('recharge', '0')),
             format_currency(v.get('deduction', '0')),
             format_currency(v.get('static_profit', '0')),
             format_currency(v.get('dynamic_profit', '0')),
             format_currency(v.get('node_profit', '0')),
             format_currency(v.get('free_coin', '0')),
             format_currency(v.get('transfer', '0')),
             format_currency(v.get('withdraw', '0')),
             format_currency(v.get('block_recharge', '0')),
             format_currency(v.get('buy_product', '0')),
             format_currency(v.get('reinvestment', '0')),
             format_currency(v.get('buy_order', '0')),
             format_currency(v.get('sell_order', '0')),
             ] for k, v in analysis_data.items()]
    day_data = sorted(data, key=lambda x: x[0])

    recharge = sum([decimal.Decimal(x[1]) for x in data])
    deduction = sum([decimal.Decimal(x[2]) for x in data])
    static_profit = sum([decimal.Decimal(x[3]) for x in data])

tdb-console/app/templates/wallet/assets.html
{% extends 'layout/main.html' %}
{% set title = '钱包列表' %}

{% block content %}

    <div class="panel bg-no">
        <form id="filter-form">
            <div class="panel-body clearfix">
                <div class="search-item">
                    <label>手机：</label>
                    {{ filter_form.mobile(class='form-control') }}
                </div>
                <div class="search-item">
                    <label>推荐码：</label>
                    {{ filter_form.uid(class='form-control') }}
                </div>
                <div class="search-item">
                    <label>币种：</label>
                    {{ filter_form.currency_code(class='form-control') }}
                </div>
                <div class="search-item">
                    <label>地址：</label>
                    {{ filter_form.address(class='form-control') }}
                </div>

                <div class="search-item search-tabtn">
                    <button type="submit" class="btn btn-primary btn-flat">查询</button>
                </div>
                {#                <div class="search-item search-tabtn">#}
                {#                    <button id="download" class="btn btn-warning">导出Excel</button>#}
                {#                </div>#}
            </div>
        </form>
    </div>
    <div class="panel panel-default">
        <div>
            <table class="table table-striped data-table font-12" id="admin-table">
                <thead>
                <tr>
                    {#                    <th><span class="row-select-checkbox"></span></th>#}
                    <th class="text-center">手机号</th>
                    <th class="text-center">推荐码</th>
                    <th class="text-center">用户昵称</th>
                    <th class="text-center">币种</th>
                    <th class="text-center">余额</th>
                    <th class="text-center">地址</th>
                    <th class="text-center" style="width: 120px">操作</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
        <script id="operation-template" type="text/template">
            <a data-id="${data}" class="label btn-danger confirm-btn">
                充值
            </a>
        </script>
    </div>

    <!-- /.table-responsive -->
{% endblock %}

{% block script %}

    <script>

        $("#download").on('click', function () {

            window.open("{{ url_for('wallet.record_download') }}?" +
                'uid=' + $('#uid').val() +
                '&wallet_type=' + $('#wallet_type').val() +
                '&type=' + $('#type').val() +
                '&created_begin_timestamp=' + $('#created_begin_timestamp').val() +
                '&created_end_timestamp=' + $('#created_end_timestamp').val());
        });
        $(function () {

            var filterForm = $('#filter-form');
            var defaultRowOptions = {className: 'v-middle text-center'};

            var $table = $('#admin-table');
            window.table = $table.DataTable(dtUtils.config({
                select: {
                    style: 'os',
                    selector: '.row-select-checkbox'
                },
                columns: [
                    dtUtils.columns.text('user.mobile', defaultRowOptions),
                    dtUtils.columns.text('user.uid', defaultRowOptions),
                    dtUtils.columns.text('user.name', defaultRowOptions),
                    dtUtils.columns.text('currency_code', defaultRowOptions),
                    dtUtils.columns.text('balance', defaultRowOptions),
                    dtUtils.columns.text('address', defaultRowOptions),
                    dtUtils.columns.tmpl('id', '#operation-template', defaultRowOptions)

                ],
                serverSide: true,
                ajax: dtUtils.dataLoader('{{ url_for('wallet.assets_ajax_list') }}', filterForm)
            }));

            filterForm.submit(function (e) {
                e.preventDefault();
                table.ajax.reload();
                return false;
            });

            $table.on('click', '.confirm-btn', function () {
                var $this = $(this);
                layer.prompt({title: '请输入充值金额'}, function (value, index) {
                    layer.close(index);
                    var loadingIndex = layer.load();
                    $.ajax({
                        type: 'POST',
                        contentType: 'application/json',
                        data: JSON.stringify({id: $this.data('id'), amount: value}),
                        url: '{{ url_for('wallet.ajax_recharge') }}',
                        success: function () {
                            layer.msg('操作成功');
                            table.ajax.reload();
                        },
                        error: function () {
                            layer.msg('操作失败');
                        }
                    }).always(function () {
                        layer.close(loadingIndex);
                    });
                });
            });
        });
    </script>
{% endblock %}

tdb-console/app/templates/wallet/withdraw.html
{% extends 'layout/main.html' %}
{% set title = '钱包记录' %}

{% block content %}


    <div class="panel bg-no">
        <form id="filter-form">
            <div class="panel-body clearfix">
                <div class="search-item">
                    <label>状态：</label>
                    {{ filter_form.status(class='form-control') }}
                </div>
                <div class="search-item">
                    <label>币种：</label>
                    {{ filter_form.currency_code(class='form-control') }}
                </div>
                <div class="search-item-date">
                    <label>时间：</label>
                    <div class="has-feedback">
                        {{ filter_form.created_begin_timestamp(class_='form-control font-12') }}
                        <span class="icon-calendar h4 no-m form-control-feedback" aria-hidden="true"></span>
                    </div>
                    <span class="date-line">-</span>
                    <div class="has-feedback">
                        {{ filter_form.created_end_timestamp(class_='form-control font-12') }}
                        <span class="icon-calendar h4 no-m form-control-feedback" aria-hidden="true"></span>
                    </div>
                </div>
                <div class="search-item search-tabtn">
                    <button type="submit" class="btn btn-primary btn-flat">查询</button>
                </div>
{#                <div class="search-item search-tabtn">#}
{#                    <button id="download" class="btn btn-warning">导出Excel</button>#}
{#                </div>#}
            </div>
        </form>
    </div>
    <div class="panel panel-default">
        <div>
            <table class="table table-striped data-table font-12" id="admin-table">
                <thead>
                <tr>
                    {#                    <th><span class="row-select-checkbox"></span></th>#}
                    <th class="text-center">时间</th>
                    <th class="text-center">用户手机</th>
                    <th class="text-center">用户昵称</th>
                    <th class="text-center">币种</th>
                    <th class="text-center">提现数量</th>
                    <th class="text-center">手续费</th>
                    <th class="text-center">提现地址</th>
                    <th class="text-center">交易哈希</th>
                    <th class="text-center">状态</th>
                    <th class="text-center" style="width: 120px">操作</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>

        <script id="operation-template" type="text/template">
            {% raw %}
            {{if row.status == 1}}
            <a data-number="${data}" class="label btn-danger confirm-btn">
                确认
            </a>
            <a data-number="${data}" class="label btn-warning cancel-btn" style="margin-left: 10px">
                驳回
            </a>
            {{/if}}
            {% endraw %}
        </script>
    </div>

    <!-- /.table-responsive -->
{% endblock %}

{% block script %}
    <!-- build:js /static/components/bootstrap-datepicker.min.js -->
    <script src="/static/components/quantum/js/bootstrap-datepicker.js"></script>
    <script src="/static/components/quantum/js/locales/bootstrap-datepicker.zh-CN.js"></script>
    <!-- endbuild -->
    <script>
        $('#created_begin_timestamp,#created_end_timestamp').datepicker({
            language: 'zh-CN'
        });

        $("#download").on('click', function () {

            window.open("{{ url_for('wallet.withdraw_download') }}?" +
                'status=' + $('#status').val() +
                '&created_begin_timestamp=' + $('#created_begin_timestamp').val() +
                '&created_end_timestamp=' + $('#created_end_timestamp').val());
        });
        $(function () {

            var statusFlag = {{ STATUS_FLAG | tojson }};
            var filterForm = $('#filter-form');
            var defaultRowOptions = {className: 'v-middle text-center'};

            var $table = $('#admin-table');
            window.table = $table.DataTable(dtUtils.config({
                select: {
                    style: 'os',
                    selector: '.row-select-checkbox'
                },
                columns: [
                    dtUtils.columns.date('created_timestamp', defaultRowOptions),
                    dtUtils.columns.text('user.mobile', defaultRowOptions),
                    dtUtils.columns.text('user.name', defaultRowOptions),
                    dtUtils.columns.text('currency_code', defaultRowOptions),
                    dtUtils.columns.float('amount', defaultRowOptions),
                    dtUtils.columns.float('fee', defaultRowOptions),
                    dtUtils.columns.text('address', defaultRowOptions),
                    dtUtils.columns.text('txid', defaultRowOptions),
                    dtUtils.columns.dict('status', statusFlag, defaultRowOptions),
                    dtUtils.columns.tmpl('number', '#operation-template', defaultRowOptions)
                ],
                serverSide: true,
                ajax: dtUtils.dataLoader('{{ url_for('wallet.ajax_withdraw_list') }}', filterForm)
            }));

            filterForm.submit(function (e) {
                e.preventDefault();
                table.ajax.reload();
                return false;
            });

            {#            $table.on('click', '.wait-btn', function () {#}
            {#                var $this = $(this);#}
            {#                layer.confirm('确定要该提现吗？', {#}
            {#                    btn: ['确认', '取消']#}
            {#                    , btn2: function (index, layero) {#}
            {#                    }#}
            {#                }, function (index) {#}
            {#                    var loadingIndex = layer.load();#}
            {#                    $.ajax({#}
            {#                        type: 'POST',#}
            {#                        contentType: 'application/json',#}
            {#                        data: JSON.stringify({id: $this.data('id'), status: 2}),#}
            {#                        url: '{{ url_for('wallet.ajax_withdraw_confirm') }}',#}
            {#                        success: function () {#}
            {#                            layer.msg('操作成功');#}
            {#                            table.ajax.reload();#}
            {#                        },#}
            {#                        error: function () {#}
            {#                            layer.msg('操作失败');#}
            {#                            window.location.reload();#}
            {#                        }#}
            {#                    }).always(function () {#}
            {#                        layer.close(loadingIndex);#}
            {#                    });#}
            {#                });#}
            {#            });#}

            $table.on('click', '.confirm-btn', function () {
                var $this = $(this);
                layer.confirm('确定已完成这笔提现吗？', {
                    btn: ['确认', '取消']
                    , btn2: function (index, layero) {
                    }
                }, function (index) {
                    var loadingIndex = layer.load();
                    $.ajax({
                        type: 'POST',
                        contentType: 'application/json',
                        data: JSON.stringify({number: $this.data('number'), status: 4}),
                        url: '{{ url_for('wallet.ajax_withdraw_confirm') }}',
                        success: function () {
                            layer.msg('操作成功');
                            table.ajax.reload();
                        },
                        error: function () {
                            layer.msg('操作失败');
                        }
                    }).always(function () {
                        layer.close(loadingIndex);
                    });
                });
            });

            $table.on('click', '.cancel-btn', function () {
                var $this = $(this);
                layer.confirm('确定驳回这笔提现吗？', {
                    btn: ['确认', '取消']
                    , btn2: function (index, layero) {
                    }
                }, function (index) {
                    var loadingIndex = layer.load();
                    $.ajax({
                        type: 'POST',
                        contentType: 'application/json',
                        data: JSON.stringify({number: $this.data('number'), status: 8}),
                        url: '{{ url_for('wallet.ajax_withdraw_cancel') }}',
                        success: function () {
                            layer.msg('操作成功');
                            table.ajax.reload();
                        },
                        error: function () {
                            layer.msg('操作失败');
                        }
                    }).always(function () {
                        layer.close(loadingIndex);
                    });
                });
            });
        });
    </script>
{% endblock %}