tdb-console/app/views/news.py
# -*- coding: utf-8 -*-
import urllib2

import requests
from flask import Blueprint, jsonify
from flask import render_template
from flask import request
from flask_wtf import Form
from wtforms import HiddenField, StringField, TextAreaField
from wtforms.validators import DataRequired

from app.views import Api, ApiError, AppError
from app.views import upload
from app.views import utils
from app.views.admin import api_permission

news = Blueprint('news', __name__)
api_permission['news'] = ['/admin/news']


class NewsForm(Form):
    id = HiddenField('Id')
    title = StringField('title', validators=[DataRequired()])
    details = TextAreaField('details', validators=[DataRequired()])


@news.route('/')
def index():
    return render_template('news/news_list.html')


@news.route('/ajax/list', methods=['POST'])
def ajax_list():
    params = request.get_json()
    data = Api.get('/admin/news', params['query'])
    total_records = data['total_count']
    return_dict = {
        'draw': params['draw'],
        'recordsTotal': total_records,
        'recordsFiltered': total_records,
        'data': data['objects']
    }
    return jsonify(return_dict)


@news.route('/details', methods=['GET'])
@news.route('/details/<string:news_id>')
def details(news_id=None):
    form = NewsForm()
    if news_id:
        news_detail = Api.get('/admin/news/details/' + urllib2.quote(news_id))
        # if news_detail['details']:
        #     detail_url = news_detail['details']
        #     response = requests.get(utils.build_oss_url(detail_url, 'http'), timeout=(9, 9))
        #     response.encoding = 'utf-8'
        #     news_detail['details'] = response.text
        form.process(data=news_detail)
    return render_template('news/detail.html', form=form)


@news.route('/ajax/save', methods=['POST'])
def ajax_save():
    form = NewsForm()
    if form.validate():
        data = form.data
        news_id = data.pop('id')
        # detail_data = data['details']
        # details_hash = utils.md5hex(detail_data)
        # data['details'] = upload.put_oss('news/%s.html' % details_hash, detail_data)
        if news_id:
            result = Api.put('/admin/news/details/' + urllib2.quote(news_id), data)
        else:
            result = Api.post('/admin/news', data)
        return jsonify(result)
    else:
        raise ApiError(AppError.INVALID_REQUEST, form.errors)


@news.route('/<news_id>', methods=['DELETE'])
def news_delete(news_id):
    result = Api.delete('/admin/news/details/' + urllib2.quote(news_id))
    return jsonify(result)

tdb-console/app/views/upload.py
# -*- coding: utf-8 -*-
import StringIO
import hashlib

import oss2 as oss2
from PIL import Image
from flask import Blueprint, jsonify, request, current_app

from app.views import utils

upload = Blueprint('upload', __name__)


@upload.route('/image/<path>', methods=['POST'])
@upload.route('/product/image', methods=['POST'])
def product_image(path=None):
    if path is None:
        path = 'game'
    resp = {'success': False, 'message': 'no image'}
    if 'image' in request.files:
        resp = __upload_image(request.files['image'], path)
    return jsonify(resp)


def __upload_image(image_file, path, private=False):
    resp = {'success': False}
    temp_buffer = StringIO.StringIO()
    try:
        image_format = __convert_image(image_file, temp_buffer)
        image_bytes = temp_buffer.getvalue()
        md5 = hashlib.md5()
        md5.update(image_bytes)
        image_hash = md5.hexdigest()
        filename = '%s.%s' % (image_hash, image_format)
        if path[-1] == '/':
            path += filename
        else:
            path += '/' + filename
        if private:
            resp['url'] = utils.build_local_url(put_oss(path, image_bytes, True))
        else:
            resp['url'] = utils.build_oss_url(put_oss(path, image_bytes), 'http')
        resp['success'] = True
    except (KeyError, IOError):
        resp['message'] = 'process image error'
    finally:
        temp_buffer.close()
    return resp


def put_oss(path, data, private=False):
    auth = oss2.Auth(current_app.config['ALIYUN_ACCESS_KEY_ID'], current_app.config['ALIYUN_ACCESS_KEY_SECRET'])
    bucket = oss2.Bucket(auth, current_app.config['OSS_ENDPOINT'], current_app.config['OSS_BUCKET'])
    root_path = current_app.config['OSS_ROOT']
    if private:
        bucket = oss2.Bucket(auth, current_app.config['OSS_ENDPOINT'], current_app.config['OSS_BUCKET_PRIVATE'])
        root_path = current_app.config['OSS_ROOT_PRIVATE']
    if root_path[:1] == '/':
        root_path = root_path[1:]
    if root_path[-1] == '/':
        root_path = root_path[0:len(root_path) - 1]
    path = root_path + (path if path[:1] == '/' else '/' + path)
    result = bucket.put_object(path, data)
    if result.status != 200:
        raise IOError(result.details['Message'])
    return path


def get_oss(path, file_name, private=False):
    auth = oss2.Auth(current_app.config['ALIYUN_ACCESS_KEY_ID'], current_app.config['ALIYUN_ACCESS_KEY_SECRET'])
    bucket = oss2.Bucket(auth, current_app.config['OSS_ENDPOINT'], current_app.config['OSS_BUCKET'])
    root_path = current_app.config['OSS_ROOT']
    if private:
        bucket = oss2.Bucket(auth, current_app.config['OSS_ENDPOINT'], current_app.config['OSS_BUCKET_PRIVATE'])
        root_path = current_app.config['OSS_ROOT_PRIVATE']
    if root_path[:1] == '/':
        root_path = root_path[1:]
    if root_path[-1] == '/':
        root_path = root_path[0:len(root_path) - 1]

    path = root_path + (path if path[:1] == '/' else '/' + path) + (
        file_name if file_name[:1] == '/' else '/' + file_name)

    result = bucket.get_object(path)
    if result.status != 200:
        raise IOError(result.details['Message'])
    return result.read()


def __convert_image(input_stream, output_stream):
    image = Image.open(input_stream)
    try:
        if image.mode in ('RGBA', 'LA') or (image.mode == 'P' and 'transparency' in image.info):
            image.save(output_stream, 'PNG')
            return 'png'
        elif image.format == 'GIF':
            image.save(output_stream, 'GIF')
            return 'gif'
        else:
            image.save(output_stream, 'JPEG')
            return 'jpg'
    finally:
        image.close()

tdb-console/app/templates/news/detail.html
{% extends 'layout/main.html' %}
{% set title = '公告详情' %}

{% block head %}
    <link rel="stylesheet" href="/static/components/quantum/summernote/summernote.css">
{% endblock %}


{% block content %}
    <div class="panel panel-default">
        <div class="panel-body">
            <form action="{{ url_for('news.ajax_save') }}" id="news_edit" method="post">
                <div class="form-horizontal font-12 mt15">
                    <div class="form-group">
                        <label class="col-xs-2 control-label"><span class="c_red">*</span>文章标题</label>
                        <div class="col-xs-10">
                            {{ form.title(class_='form-control w400 inline_block') }}
                            <span class="ml20">标题长度5-30个中文字</span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-xs-2 control-label"><span class="c_red">*</span>文章内容编辑</label>
                        <div class="col-xs-10">
                            {{ form.details() }}
                        </div>
                    </div>
                    <div class="form-group">
                        {{ form.hidden_tag() }}
                        <label class="col-xs-2 control-label"></label>
                        <div class="col-xs-10">
                            <button type="submit" class="btn btn-primary btn-flat">发布</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block script %}
        <script src="/static/components/quantum/summernote/summernote.js"></script>
        <script src="/static/components/quantum/summernote/lang/summernote-zh-CN.js"></script>
        <script src="/static/assets/js/summernote-upload.js"></script>
    <script>

        var imageUploadUrl = '{{ url_for('upload.product_image', path='campaign') }}';
        var detailEditor = createUploadEditor('#details', imageUploadUrl);
        var realEditor = detailEditor.next('.note-editor');
        var news_edit = $('#news_edit');

        news_edit.submit(function (e) {
            e.preventDefault();
            {#$('#details').val(detailEditor.summernote('code'));#}
            var submit_button = $(this).find('button[type="submit"]');
            submit_button.button('loading');
            news_edit.resetFieldErrors()
                .ajaxSubmit(function () {
                    layer.msg('操作成功');
                    window.location.href = "{{ url_for('news.index') }}";
                }).error(function (xhr) {
                if (news_edit.applyFieldErrors(xhr, {

                    handler: 'popover-and-highlight'
                })) {
                    layer.msg('信息填写错误');
                }
            }).always(function () {
                submit_button.button('reset');
            });
        });
    </script>
{% endblock %}

tdb-console/app/templates/news/news_list.html
{% extends 'layout/main.html' %}
{% set title = '公告列表' %}

{% block content %}

    <div class="panel panel-default">
        <div>
            <table class="table table-striped data-table font-12" id="admin-table">
                <thead>
                <tr>
                    <th class="text-center">标题</th>
                    <th class="text-center">时间</th>
                    <th class="text-center">操作</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>

    <script id="table-template" type="text/template">
        <div>
            <a href="{{ url_for('news.details',news_id='') }}${data}">
                <label class="label btn-primary">查看详情</label>
            </a>
            <a data-id="${data}">
                <label class="label btn-danger">删除</label>
            </a>
        </div>

    </script>

    <!-- /.table-responsive -->
{% endblock %}

{% block script %}
    <script src="/static/components/quantum/summernote/summernote.js"></script>
    <script src="/static/components/quantum/summernote/lang/summernote-zh-CN.js"></script>
    <script src="/static/assets/js/summernote-upload.js"></script>
    <script>
        $(function () {
            var defaultRowOptions = {className: 'v-middle text-center'};
            var $table = $('#admin-table');
            window.table = $table.DataTable(dtUtils.config({
                select: {
                    style: 'os',
                    selector: '.row-select-checkbox'
                },
                columns: [
                    dtUtils.columns.text('title', defaultRowOptions),
                    dtUtils.columns.date('created_timestamp', defaultRowOptions),
                    dtUtils.columns.tmpl('id', '#table-template', defaultRowOptions)
                ],
                serverSide: true,
                ajax: dtUtils.dataLoader('{{ url_for('news.ajax_list') }}')
            }));


            $table.on('click', '.btn-danger', function () {
                var news_id = $(this).closest('a').data('id');
                var btn = $(this);

                layer.confirm('确认要删除吗？', {
                    btn: ['确认', '取消'] //按钮
                }, function (index, layero) {
                    layer.close(index);
                    btn.button('loading');
                    $.ajax({
                        url: "{{ url_for('news.news_delete', news_id='') }}" + news_id,
                        type: 'DELETE',
                        json: true,
                        contentType: 'application/json',
                        success: function (data) {
                            table.ajax.reload();
                        }
                    }).always(function (data) {
                        btn.button('reset');
                    });
                });
            });
        });
    </script>
{% endblock %}