tdb-console/app/views/message.py
# -*- coding: utf-8 -*-
import urllib2

from flask import Blueprint, jsonify
from flask import render_template
from flask import request
from flask_wtf import Form
from wtforms import StringField, SelectField, TextAreaField, HiddenField
from wtforms.validators import DataRequired

from app.views import Api, ApiError, AppError
from app.views.admin import api_permission

message = Blueprint('message', __name__)
api_permission['message'] = ['/admin/message', '/admin/member']

# 1 管理员端未读 2 管理员已读并忽略  4 管理员已读并回复  8 会员端已读回复

STATUS_FLAG = [(1, u'未读 '),
               (2, u'已读'),
               (4, u'已回复'),
               (8, u'会员已读回复')]


class FilterForm(Form):
    title = StringField('title')
    status = SelectField('status', choices=[(0, u'全部')] + STATUS_FLAG, coerce=int)
    uid = StringField('uid')


class MessageForm(Form):
    id = HiddenField('id')
    answer = TextAreaField('answer', validators=[DataRequired(message='请填写回复内容')])


class RegisterForm(Form):
    uid = StringField('uid', validators=[DataRequired(u'请填写编号')])
    mobile = StringField('mobile', validators=[DataRequired(u'请填写手机号')])
    sponsor = StringField('sponsor', validators=[DataRequired(u'请填写推荐人')])
    placement = StringField('placement', validators=[DataRequired(u'请填写安置上线')])
    position = SelectField('position', choices=[(0, u'左'), (1, u'右')], coerce=int)
    # rate_level = SelectField('rate_level', choices=RATE_LEVEL_FLAG)
    password = StringField('password', validators=[DataRequired(u'请填写密码')])
    security_password = StringField('security_password', validators=[DataRequired(u'请填写密码')])


@message.route('/')
def index():
    filter_form = FilterForm()
    return render_template('message/index.html',
                           filter_form=filter_form,
                           STATUS_FLAG=dict(STATUS_FLAG))


@message.route('/ajax/list', methods=['POST'])
def ajax_list():
    params = request.get_json()
    data = Api.get('/admin/message', params['query'])
    total_records = data['total']
    return_dict = {
        'draw': params['draw'],
        'recordsTotal': total_records,
        'recordsFiltered': total_records,
        'data': data['items']
    }
    return jsonify(return_dict)


@message.route('/details/<string:message_id>')
def details(message_id=None):
    form = MessageForm()
    message_detail = Api.get('/admin/message/detail/' + urllib2.quote(message_id))
    form.process(data=message_detail)
    return render_template('message/detail.html',
                           message_detail=message_detail,
                           form=form)


@message.route('/ajax/save', methods=['POST'])
def ajax_save():
    form = MessageForm()
    if form.validate():
        data = form.data
        message_id = data.pop('id')
        result = Api.put('/admin/message/detail/' + urllib2.quote(message_id), data)
        return jsonify(result)
    else:
        raise ApiError(AppError.INVALID_REQUEST, form.errors)


# @message.route('/register/member')
def register_member():
    form = RegisterForm()
    return render_template('member/register.html', form=form)


# @message.route('/ajax/register_member', methods=['POST'])
def ajax_register_member():
    form = RegisterForm()
    if form.validate():
        data = form.data
        return jsonify(Api.post('/admin/member', data))
    else:
        raise ApiError(AppError.INVALID_REQUEST, form.errors)

tdb-console/app/views/news.py
# -*- coding: utf-8 -*-
import urllib2

import requests
from flask import Blueprint, jsonify
from flask import render_template
from flask import request
from flask_wtf import Form
from wtforms import HiddenField, StringField, TextAreaField
from wtforms.validators import DataRequired

from app.views import Api, ApiError, AppError
from app.views import upload
from app.views import utils
from app.views.admin import api_permission

news = Blueprint('news', __name__)
api_permission['news'] = ['/admin/news']


class NewsForm(Form):
    id = HiddenField('Id')
    title = StringField('title', validators=[DataRequired()])
    details = TextAreaField('details', validators=[DataRequired()])


@news.route('/')
def index():
    return render_template('news/news_list.html')


@news.route('/ajax/list', methods=['POST'])
def ajax_list():
    params = request.get_json()
    data = Api.get('/admin/news', params['query'])
    total_records = data['total_count']
    return_dict = {
        'draw': params['draw'],
        'recordsTotal': total_records,
        'recordsFiltered': total_records,
        'data': data['objects']
    }
    return jsonify(return_dict)


@news.route('/details', methods=['GET'])
@news.route('/details/<string:news_id>')
def details(news_id=None):
    form = NewsForm()
    if news_id:
        news_detail = Api.get('/admin/news/details/' + urllib2.quote(news_id))
        # if news_detail['details']:
        #     detail_url = news_detail['details']
        #     response = requests.get(utils.build_oss_url(detail_url, 'http'), timeout=(9, 9))
        #     response.encoding = 'utf-8'
        #     news_detail['details'] = response.text
        form.process(data=news_detail)
    return render_template('news/detail.html', form=form)


@news.route('/ajax/save', methods=['POST'])
def ajax_save():
    form = NewsForm()
    if form.validate():
        data = form.data
        news_id = data.pop('id')
        # detail_data = data['details']
        # details_hash = utils.md5hex(detail_data)
        # data['details'] = upload.put_oss('news/%s.html' % details_hash, detail_data)
        if news_id:
            result = Api.put('/admin/news/details/' + urllib2.quote(news_id), data)
        else:
            result = Api.post('/admin/news', data)
        return jsonify(result)
    else:
        raise ApiError(AppError.INVALID_REQUEST, form.errors)


@news.route('/<news_id>', methods=['DELETE'])
def news_delete(news_id):
    result = Api.delete('/admin/news/details/' + urllib2.quote(news_id))
    return jsonify(result)

tdb-console/app/templates/message/detail.html
{% extends 'layout/main.html' %}
{% set title = '消息详情' %}

{% block head %}
    <link rel="stylesheet" href="/static/components/quantum/summernote/summernote.css">
{% endblock %}


{% block content %}
    <div class="panel panel-default">
        <div class="panel-body">
            <form action="{{ url_for('message.ajax_save') }}" id="message_edit" method="post">
                <div class="form-horizontal font-12 mt15">
                    <div class="form-group">
                        <label class="col-xs-2 control-label">用户</label>
                        <div class="col-xs-10" style="padding-top: 8px">
                                {{ message_detail.user.uid }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-2 control-label">昵称</label>
                        <div class="col-xs-10" style="padding-top: 8px">
                                {{ message_detail.user.nickname }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-2 control-label">手机</label>
                        <div class="col-xs-10" style="padding-top: 8px">
                                {{ message_detail.user.mobile }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-2 control-label">时间</label>
                        <div class="col-xs-10" style="padding-top: 8px">
                                {{ message_detail.created_timestamp | timestamp_to_str }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-2 control-label">标题</label>
                        <div class="col-xs-10" style="padding-top: 8px">
                                {{ message_detail.title }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-2 control-label">问题</label>
                        <div class="col-xs-10" style="padding-top: 8px">
                                {{ message_detail.question }}
                        </div>
                    </div>


                    <div class="form-group">
                        <label class="col-xs-2 control-label"><span class="c_red">*</span>回复内容</label>
                        <div class="col-xs-10">
                            {{ form.answer(style="height: 100px; width: 400px;") }}
                        </div>
                    </div>
                    <div class="form-group">
                        {{ form.hidden_tag() }}
                        <label class="col-xs-2 control-label"></label>
                        <div class="col-xs-10">
                            <button type="submit" class="btn btn-primary btn-flat">回复</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block script %}

    <script>

        var message_edit = $('#message_edit');

        message_edit.submit(function (e) {
            e.preventDefault();
            var submit_button = $(this).find('button[type="submit"]');
            submit_button.button('loading');
            message_edit.resetFieldErrors()
                    .ajaxSubmit(function () {
                        layer.msg('操作成功');
                        window.location.href = "{{ url_for('message.index') }}";
                    }).error(function (xhr) {
                if (message_edit.applyFieldErrors(xhr, {
                            handler: 'popover-and-highlight'
                        })) {
                    layer.msg('信息填写错误');
                }
            }).always(function () {
                submit_button.button('reset');
            });
        });
    </script>
{% endblock %}

tdb-console/app/templates/message/index.html
{% extends 'layout/main.html' %}
{% set title = '消息列表' %}

{% block content %}
    <div class="panel bg-no">
        <form id="filter-form" method="get">
            <div class="panel-body clearfix">
                <div class="search-item">
                    <label>标题：</label>
                    {{ filter_form.title(class_='form-control') }}
                </div>
                <div class="search-item">
                    <label>用户编号：</label>
                    {{ filter_form.uid(class_='form-control') }}
                </div>
                <div class="search-item">
                    <label>状态：</label>
                    {{ filter_form.status(class_='form-control') }}
                </div>
                <div class="search-item search-tabtn">
                    <button id="search" type="submit" class="btn btn-primary btn-flat">查询</button>
                </div>
            </div>
        </form>
    </div>
    <div class="panel panel-default">
        <div>
            <table class="table table-striped data-table font-12" id="admin-table">
                <thead>
                <tr>
                    <th class="text-center">时间</th>
                    <th class="text-center">用户编号</th>
                    <th class="text-center">用户手机</th>
                    <th class="text-center">标题</th>
                    <th class="text-center">状态</th>
                    <th class="text-center">操作</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>

    <script id="table-template" type="text/template">
        <div>
            <a href="{{ url_for('message.details',message_id='') }}${data}" target="_blank">
                <label class="label btn-primary">查看详情</label>
            </a>
{#            <a data-id="${data}">#}
{#                <label class="label btn-danger">删除</label>#}
{#            </a>#}
        </div>

    </script>

    <!-- /.table-responsive -->
{% endblock %}

{% block script %}
    <script src="/static/components/quantum/summernote/summernote.js"></script>
    <script src="/static/components/quantum/summernote/lang/summernote-zh-CN.js"></script>
    <script src="/static/assets/js/summernote-upload.js"></script>
    <script>
        $(function () {
            var defaultRowOptions = {className: 'v-middle text-center'};
            var $table = $('#admin-table');
            var filterForm = $('#filter-form');
            window.table = $table.DataTable(dtUtils.config({
                select: {
                    style: 'os',
                    selector: '.row-select-checkbox'
                },
                columns: [
                    dtUtils.columns.date('created_timestamp', defaultRowOptions),
                    dtUtils.columns.text('user.uid', defaultRowOptions),
                    dtUtils.columns.text('user.mobile', defaultRowOptions),
                    dtUtils.columns.text('title', defaultRowOptions),
                    dtUtils.columns.dict('status', {{ STATUS_FLAG | tojson }}, defaultRowOptions),
                    dtUtils.columns.tmpl('id', '#table-template', defaultRowOptions)
                ],
                serverSide: true,
                ajax: dtUtils.dataLoader('{{ url_for('message.ajax_list') }}', filterForm)
            }));
            filterForm.submit(function (e) {
                e.preventDefault();
                table.ajax.reload();
                return false;
            });


            $table.on('click', '.btn-danger', function () {
                var news_id = $(this).closest('a').data('id');
                var btn = $(this);

                layer.confirm('确认要删除吗？', {
                    btn: ['确认', '取消'] //按钮
                }, function (index, layero) {
                    layer.close(index);
                    btn.button('loading');
                    $.ajax({
                        url: "{{ url_for('news.news_delete', news_id='') }}" + news_id,
                        type: 'DELETE',
                        json: true,
                        contentType: 'application/json',
                        success: function (data) {
                            table.ajax.reload();
                        }
                    }).always(function (data) {
                        btn.button('reset');
                    });
                });
            });
        });
    </script>
{% endblock %}